### ISSUE TITLE
Change output format to anything else other than AAC

### ISSUE THREAD

**Issue by day-dreaming-guy** [bilalbakhrom/SoundControlKit#11]
Hey! love the library. Is it possible to change the output format to anything else? 

Thank you!

**Comment by bilalbakhrom** [comment]
@day-dreaming-guy Hey! Thank you for your kind words about the library. Now you can change the output format to different options like **.wav**, **.flac**, **.aac**, and **.m4a**. This feature is available from version 2.1.0.

**Comment by day-dreaming-guy** [comment]
Hey @bilalbakhrom ! Thank you for that :)
It’s a great feature!

A small question: I’m building an app that focuses mostly on user voice recording—I was wondering if you could provide a paid consultation regarding overall audio recording from an iPhone, as I see that you are very knowledgeable in this field. Is it possible to schedule a 15-minute Zoom call (paid, of course)?

**Comment by bilalbakhrom** [comment]
@day-dreaming-guy  You can reach me at Telegram: https://t.me/bilalbakhrom
